# Generated by Django 4.2.16 on 2024-11-29 10:43

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(default=django.db.models.expressions.CombinedExpression(models.F('time'), '+', models.Value(datetime.timedelta(days=1))))),
                ('user_profile', models.CharField(max_length=255)),
            ],
        ),
    ]
