# Generated by Django 5.1.3 on 2024-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_remove_attraction_location_attraction_address_string_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image_url',
        ),
        migrations.AddField(
            model_name='attraction',
            name='awards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attraction',
            name='photo_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
