# Generated by Django 4.2.16 on 2024-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0004_remove_attraction_image_url_attraction_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='trip_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
