# Generated by Django 4.2.16 on 2024-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_attraction_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
